[features]
seeds = false
skip-lint = false
[programs.localnet]
market_place = "DApTMHgStwAesfm92JNo9JQkMg7rVS83jwa2rxiegFix"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/hackerboy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
